server:
  port: 8082

spring:
  application:
    name: edu-ucenterservice

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # TODO: 需修改数据库账号密码
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu?characterEncoding=utf-8&useSSL=false
    username: root
    password: 11111



    ### 配置Redis
    # Redis数据库索引（默认为0）
    redis:
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # 配置连接池
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池中的最小空闲连接
          min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 2000
      lettuce:
        shutdown-timeout: 0


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#wx:
#  open:
#    app_id: wxc606fb748aedee7c
#
#    app_secret: 6c94e426cc7f49e29b42231ee202b1a3
#
#    redirect_url: http://yaohuan.work/api/ucenter/wx/callback

# TODO: 需修改微信小程序或微博APPID信息
wx:
  open:
    app_id: wx07dd54b370ca15ce

    app_secret: d9bf6a98cdf50451d51dd9d0278c34d0

    redirect_url: http://yaohuan.work/api/ucenter/wx/callback
wb:
  open:
    app_key:
    app_secret:
    redirect_url:



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/  #指定注册中心地址
  instance:
    prefer-ip-address: true   #eureka服务器上获取的是服务器的ip地址，否则是主机名